<?php

namespace AppBundle\Repository;

/**
 * JWTRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class JWTRepository extends \Doctrine\ORM\EntityRepository
{
}
