imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: fr_FR

framework:
    #esi:             ~
    translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # http://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id:  session.handler.native_file
        save_path:   "%kernel.root_dir%/../var/sessions/%kernel.environment%"
    fragments:       ~
    http_method_override: true
    assets: ~

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    globals:
        site_name:    "%site_name%"
        site_author:  "%site_author%"
        mailer_from:  "%mailer_from%"
        analytics:    "%analytics%"
    form_themes:
        - bootstrap_3_layout.html.twig
        - TilowebBase64Bundle:form:fields.html.twig
        - VichUploaderBundle:Form:fields.html.twig

# Doctrine Configuration
doctrine:
    dbal:
        url: "%database_url%"
    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

# liip imagine Configuration
liip_imagine:
    resolvers:
        default:
            web_path: ~
    filter_sets:
        cache: ~
        # Thumbnail filter set configuration
        thumbnail:
            quality: 90
            filters:
                thumbnail: { size: [300, 300], mode: outbound }
        # ThetaS filter set configuration
        thumbnail_thetas:
            quality: 90
            filters:
                crop:
                    size: [ 800, 800 ]
                    # Original ThetaS size : 5376 x 2688
                    start: [ 2288, 944 ]
                thumbnail: { size: [300, 300], mode: outbound }
        # Scale down oversized pictures
        resize:
            filters:
                downscale:
                    max: [ 1920, 1200 ]

# backend filtering
        # Thumbnail filter set configuration
        thumbnail_backend:
            data_loader: binary_image_data_loader
            quality: 75
            filters:
                thumbnail: { size: [300, 300], mode: outbound }
        # ThetaS filter set configuration
        thumbnail_thetas_backend:
            data_loader: binary_image_data_loader
            quality: 75
            filters:
                crop:
                    size: [ 800, 800 ]
                    # Original ThetaS size : 5376 x 2688
                    start: [ 2288, 944 ]
                thumbnail: { size: [300, 300], mode: outbound }
        resize_backend:
            data_loader: binary_image_data_loader
            filters:
                downscale:
                    max: [ 1920, 1200 ]

vich_uploader:
    db_driver: orm
    mappings:
        image_upload:
            uri_prefix:         /uploads/images
            upload_destination: %kernel.root_dir%/../web/uploads/images
            namer:              vich_uploader.namer_uniqid
            inject_on_load:     false
            delete_on_update:   true
            delete_on_remove:   true
        document_upload:
            uri_prefix:         /uploads/documents
            upload_destination: %kernel.root_dir%/../web/uploads/documents
            namer:              vich_uploader.namer_uniqid
            inject_on_load:     false
            delete_on_update:   true
            delete_on_remove:   true
