tangoman_test:
    resource: "@TangoManTestBundle/Controller/"
    type:     annotation

tangoman_user:
    resource: "@TangoManUserBundle/Controller/"
    type:     annotation

api:
    resource: "@ApiBundle/Controller/"
    type:     annotation

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.xml"
