# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:

    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        AppBundle\Entity\User:
            algorithm: bcrypt

    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
        database:
            entity:
                class: AppBundle:User

    role_hierarchy:
            ROLE_SUPER_USER:  [ROLE_USER]
            ROLE_ADMIN:       [ROLE_USER, ROLE_SUPER_USER]
            ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_SUPER_USER, ROLE_ADMIN]

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        admin:
            anonymous: ~
            provider: database
            pattern: ^/
            form_login:
                login_path: app_login
                check_path: app_check
                default_target_path: homepage
            logout:
                path: app_logout
                target: homepage
                invalidate_session: true

        main:
            anonymous: ~

    access_control:
        - { path: '^/admin', roles: [ROLE_ADMIN] }
        - { path: '^/super-admin', roles: [ROLE_SUPER_ADMIN] }
