# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    em:
        class: AppBundle\Service\EntityManagerService
        arguments: ["@doctrine.orm.entity_manager"]

    services.string_helper:
        class: AppBundle\Service\StringHelperService

    services.csv_reader:
        class: AppBundle\Service\CSVReaderService

    app.form.type.task:
        class: AppBundle\Form\Admin\AdminEditUserType
        arguments: ["@doctrine.orm.entity_manager"]
        tags:
            - { name: form.type }

    twig.extension.callback:
        class: AppBundle\TwigExtension\Callback
        tags:
            - { name: twig.extension }

    twig.extension.text:
           class: Twig_Extensions_Extension_Text
           tags:
                - { name: twig.extension }
