# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    em:
        class: AppBundle\Services\EntityManagerService
        arguments: ["@doctrine.orm.entity_manager"]

    jwt:
        class: AppBundle\Services\JWTService
        arguments: [%secret%, "@router"]

#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]

    twig.extension.remove_url_query:
        class: AppBundle\TwigExtension\RemoveUrlQuery
        tags:
            - { name: twig.extension }
