# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    em:
        class: AppBundle\Service\EntityManagerService
        arguments: ["@doctrine.orm.entity_manager"]

    twig.extension.remove_query:
        class: AppBundle\TwigExtension\RemoveQuery
        tags:
            - { name: twig.extension }

    twig.extension.callback:
        class: AppBundle\TwigExtension\Callback
        tags:
            - { name: twig.extension }

    twig.extension.text:
           class: Twig_Extensions_Extension_Text
           tags:
                - { name: twig.extension }

    services.csv_reader:
        class: AppBundle\Service\CSVReaderService
