# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    em:
        class: AppBundle\Services\EntityManagerService
        arguments: ["@doctrine.orm.entity_manager"]

    twig.extension.remove_url_query:
        class: AppBundle\TwigExtension\RemoveUrlQuery
        tags:
            - { name: twig.extension }

    services.csv_reader:
        class: AppBundle\Services\CSVReaderService
